export enum Platform {
  WEB = 'WEB',
  MOBILE_IOS = 'MOBILE_IOS',
  MOBILE_ANDROID = 'MOBILE_ANDROID',
  ADMIN = 'ADMIN',
}

export enum TxType {
  INTERNAL = 'INTERNAL',
  EXTERNAL_SEND = 'EXTERNAL_SEND',
  EXTERNAL_RECEIVE = 'EXTERNAL_RECEIVE',
  DEPOSIT = 'DEPOSIT',
  SWEEP = 'SWEEP',
}

export enum TxStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
}

export enum WithdrawalStatus {
  PENDING_24H = 'PENDING_24H',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  OPERATOR = 'OPERATOR',
  VIEWER = 'VIEWER',
}

export enum WalletLockStatus {
  LOCKED = 'LOCKED',
  UNLOCKED = 'UNLOCKED',
}

export enum NotificationType {
  DEPOSIT = 'DEPOSIT',
  SEND_COMPLETE = 'SEND_COMPLETE',
  RECEIVE = 'RECEIVE',
  WITHDRAWAL_PENDING = 'WITHDRAWAL_PENDING',
  WITHDRAWAL_APPROVED = 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED = 'WITHDRAWAL_REJECTED',
  WITHDRAWAL_COMPLETE = 'WITHDRAWAL_COMPLETE',
  WALLET_LOCKED = 'WALLET_LOCKED',
  WALLET_UNLOCKED = 'WALLET_UNLOCKED',
  SYSTEM = 'SYSTEM',
  PRICE_ALERT = 'PRICE_ALERT',
}
